version: '3'
services:
  web:
    build: site
    container_name: apache-3IW
    ports :
     - "80:80"
    volumes:
     - ${PWD}/www:/var/www/html/
     - ${PWD}/server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ${PWD}/server/apache2.conf:/etc/apache2/apache2.conf
     - ${PWD}/server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
         - database

  database:
    image: mysql:5.7
    container_name: mysql-mvc
    environment:
      MYSQL_DATABASE: mvcdocker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ${PWD}/db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-mvc
    depends_on:
      - database
    ports:
      - 8081:80
    environment:
        - PMA_ARBITRARY=1
